#include "common/camera.h"
#include "common/color.h"
#include "common/ray.h"
#include "common/vec3.h"
#include "material/dielectric.h"
#include "material/lambertian.h"
#include "material/material.h"
#include "material/metal.h"
#include "object/hit_record.h"
#include "object/hittable.h"
#include "object/hittable_list.h"
#include "object/sphere.h"
// #include "util/rtweekend.hpp"